name = "HashpipeIBVerbs"
uuid = "541072a2-e030-4f61-8d9e-ac74cf1c2f98"
authors = ["David MacMahon <davidm@astro.berkeley.edu>"]
version = "0.1.0"

[deps]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"
